FROM centos:7

# Install ssh server
RUN yum -y install openssh-server

# Setup user
RUN useradd remote_user && echo "qwerty" | passwd remote_user --stdin

# create .ssh folder for the remote_user user
RUN mkdir /home/remote_user/.ssh && chmod 700 /home/remote_user/.ssh

# Setup ssh key
COPY remote-key.pub /home/remote_user/.ssh/authorized_keys

# Setup permissions
RUN chown remote_user:remote_user -R /home/remote_user && \
    chmod 600 /home/remote_user/.ssh/authorized_keys

# "sshd: no hostkeys available" [fix error]
RUN /usr/sbin/sshd-keygen > /dev/null 2>&1

CMD /usr/sbin/sshd -D